set(SDK_PATH "/Volumes/Resources/stash/matter/blue/third_party/silabs/simplicity_sdk")
set(COPIED_SDK_PATH "simplicity_sdk_2024.6.0")

add_library(slc_generator OBJECT
    "${SDK_PATH}/../../../examples/platform/silabs/provision/AttestationKeyMbed.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionChannelRTT.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionEncoder.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionManager.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV1.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionProtocolV2.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorage.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageCustom.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/provision/ProvisionStorageFlash.cpp"
    "${SDK_PATH}/../../../examples/platform/silabs/syscalls_stubs.cpp"
    "${SDK_PATH}/../../../src/lib/support/Base64.cpp"
    "${SDK_PATH}/../../../src/lib/support/BytesToHex.cpp"
    "${SDK_PATH}/../../../src/lib/support/logging/TextOnlyLogging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/Logging.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SilabsConfig.cpp"
    "${SDK_PATH}/../../../src/platform/silabs/SiWx917/CHIPCryptoPALTinyCrypt.cpp"
    "${SDK_PATH}/../../../src/setup_payload/Base38Encode.cpp"
    "${SDK_PATH}/../../mbedtls/repo/library/aes.c"
    "${SDK_PATH}/../../mbedtls/repo/library/asn1parse.c"
    "${SDK_PATH}/../../mbedtls/repo/library/asn1write.c"
    "${SDK_PATH}/../../mbedtls/repo/library/base64.c"
    "${SDK_PATH}/../../mbedtls/repo/library/bignum.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ccm.c"
    "${SDK_PATH}/../../mbedtls/repo/library/cipher.c"
    "${SDK_PATH}/../../mbedtls/repo/library/cipher_wrap.c"
    "${SDK_PATH}/../../mbedtls/repo/library/constant_time.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ctr_drbg.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecdh.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecdsa.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecp.c"
    "${SDK_PATH}/../../mbedtls/repo/library/ecp_curves.c"
    "${SDK_PATH}/../../mbedtls/repo/library/entropy.c"
    "${SDK_PATH}/../../mbedtls/repo/library/hkdf.c"
    "${SDK_PATH}/../../mbedtls/repo/library/hmac_drbg.c"
    "${SDK_PATH}/../../mbedtls/repo/library/md.c"
    "${SDK_PATH}/../../mbedtls/repo/library/pem.c"
    "${SDK_PATH}/../../mbedtls/repo/library/pkcs5.c"
    "${SDK_PATH}/../../mbedtls/repo/library/platform.c"
    "${SDK_PATH}/../../mbedtls/repo/library/sha256.c"
    "${SDK_PATH}/../../mbedtls/repo/library/sha512.c"
    "${SDK_PATH}/../../mbedtls/repo/library/x509.c"
    "${SDK_PATH}/../../mbedtls/repo/library/x509_create.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc_dh.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/ecc_dsa.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/error.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/oid.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pk.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pk_wrap.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pkparse.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/pkwrite.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/platform_util.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/x509_crt.c"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/src/x509write_csr.c"
    "${SDK_PATH}/../matter_support/matter/si91x/siwx917/BRD4338A/support/src/startup_common_RS1xxxx.c"
    "${SDK_PATH}/../wifi_sdk/components/board/silabs/src/rsi_board.c"
    "${SDK_PATH}/../wifi_sdk/components/common/src/sl_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/ipmu_apis.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/iPMU_prog/iPMU_dotc/rsi_system_config_917.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_deepsleep_soc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/rsi_ps_ram_func.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/startup_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/src/system_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/common/src/rsi_debug.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/common/src/sl_si91x_stack_object_declare.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/config/src/rsi_nvic_priorities_config.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/UDMA.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/USART.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/clock_update.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_crc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_egpio.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_udma_wrapper.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/src/rsi_usart.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_common_flash_intf.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/src/sl_si91x_nvm3_hal_flash.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ipmu.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_pll.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_temp_sensor.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/src/rsi_ulpss_clk.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_ram.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/rsi_hal_mcu_m4_rom.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_platform_wireless.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_bus.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sl_si91x_timer.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/src/sli_siwx917_soc.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/errno/src/sl_si91x_errno.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade/firmware_upgradation.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/host_mcu/si91x/siwx917_soc_ncp_host.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/icmp/sl_net_ping.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/memory/malloc_buffers.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_rsi_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_net_si91x_integration_handler.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_credentials.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/src/sl_si91x_net_internal_stack.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_rsi_utility.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_callback_framework.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/src/sl_si91x_driver.c"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/threading/sli_si91x_multithreaded.c"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/si91x/sl_wifi.c"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/src/sl_wifi_callback_framework.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/si91x/sl_net_si91x.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_certificate_store.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_credentials.c"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/src/sl_net_basic_profiles.c"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Source/os_systick.c"
    "${SDK_PATH}/platform/common/src/sl_assert.c"
    "${SDK_PATH}/platform/common/src/sl_core_cortexm.c"
    "${SDK_PATH}/platform/common/src/sl_slist.c"
    "${SDK_PATH}/platform/common/src/sl_string.c"
    "${SDK_PATH}/platform/common/src/sli_cmsis_os2_ext_task_register.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_default_common_linker.c"
    "${SDK_PATH}/platform/emdrv/nvm3/src/nvm3_lock.c"
    "${SDK_PATH}/platform/emlib/src/em_core.c"
    "${SDK_PATH}/platform/service/device_init/src/sl_device_init_nvic.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream.c"
    "${SDK_PATH}/platform/service/iostream/src/sl_iostream_rtt.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_init.c"
    "${SDK_PATH}/platform/service/system/src/sl_system_kernel.c"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Source/cmsis_os2.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/croutine.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/event_groups.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/list.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F/port.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/MemMang/heap_3.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/queue.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/stream_buffer.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/tasks.c"
    "${SDK_PATH}/util/third_party/freertos/kernel/timers.c"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER/SEGGER_RTT.c"
    "../../../generator/app.cpp"
    "../../../generator/main.cpp"
    "../../../generator/si917.cpp"
    "../autogen/sl_event_handler.c"
    "../autogen/sl_iostream_handles.c"
)

target_include_directories(slc_generator PUBLIC
   "../config"
   "../autogen"
   "../../../generator"
    "${SDK_PATH}/../../../examples"
    "${SDK_PATH}/../../../examples/platform/silabs"
    "${SDK_PATH}/../../../src"
    "${SDK_PATH}/../../../src/platform/silabs/SiWx917"
    "${SDK_PATH}/../../../src/include"
    "${SDK_PATH}/../../../zzz_generated/app-common"
    "${SDK_PATH}/../../nlassert/repo/include"
    "${SDK_PATH}/../../nlio/repo/include"
    "${SDK_PATH}/../matter_support/matter/mbedtls/tinycrypt/inc"
    "${SDK_PATH}/../../mbedtls/repo/library"
    "${SDK_PATH}/../../mbedtls/repo/include"
    "${SDK_PATH}/../../../src/lib/support"
    "${SDK_PATH}/../../../src/platform/silabs"
    "${SDK_PATH}/../matter_support/matter/si91x/siwx917/BRD4338A/support/inc"
    "${SDK_PATH}/../wifi_sdk/components/service/bsd_socket/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver/CMSIS/Driver/Include"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/cmsis_driver"
    "${SDK_PATH}/../wifi_sdk/components/service/network_manager/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/rom_driver/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/chip/inc"
    "${SDK_PATH}/../wifi_sdk/components/board/silabs/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/peripheral_drivers/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/config"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/core/common/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/service/nvm3/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/errno/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/icmp"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/firmware_upgrade"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/sl_net/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/wireless/ahb_interface/inc"
    "${SDK_PATH}/../wifi_sdk/components/device/silabs/si91x/mcu/drivers/systemlevel/inc"
    "${SDK_PATH}/../wifi_sdk/components/protocol/wifi/inc"
    "${SDK_PATH}/../wifi_sdk/resources/certificates"
    "${SDK_PATH}/../wifi_sdk/resources/html"
    "${SDK_PATH}/../wifi_sdk/resources/other"
    "${SDK_PATH}/../wifi_sdk/components/common/inc"
    "${SDK_PATH}/platform/common/inc"
    "${SDK_PATH}/platform/CMSIS/Core/Include"
    "${SDK_PATH}/platform/CMSIS/RTOS2/Include"
    "${SDK_PATH}/platform/service/device_init/inc"
    "${SDK_PATH}/platform/emdrv/common/inc"
    "${SDK_PATH}/platform/emlib/inc"
    "${SDK_PATH}/util/third_party/freertos/cmsis/Include"
    "${SDK_PATH}/util/third_party/freertos/kernel/include"
    "${SDK_PATH}/util/third_party/freertos/kernel/portable/GCC/ARM_CM4F"
    "${SDK_PATH}/platform/service/iostream/inc"
    "${SDK_PATH}/platform/emdrv/nvm3/inc"
    "${SDK_PATH}/util/third_party/segger/systemview/SEGGER"
    "${SDK_PATH}/platform/service/system/inc"
)

target_compile_definitions(slc_generator PUBLIC
    CHIP_SYSTEM_CONFIG_USE_SOCKETS=1
    DEBUG_EFM=1
    MBEDTLS_CONFIG_FILE="siwx917-chip-tinycrypt-config.h"
    NVM3_LOCK_OVERRIDE=1
    OPTIMIZE_TINYCRYPT_ASM=1
    SILABS_PROVISION_PROTOCOL_V1=0
    SL_MBEDTLS_USE_TINYCRYPT=1
    SL_PROVISION_CHANNEL_ENABLED=1
    SL_PROVISION_GENERATOR=1
    TINYCRYPT_PRIMITIVES=1
    SIWG917M111MGTBA=1
    SLI_SI917=1
    SLI_SI917B0=1
    SLI_SI91X_MCU_ENABLE_FLASH_BASED_EXECUTION=1
    SLI_SI91X_MCU_EXTERNAL_LDO_FOR_PSRAM=1
    SLI_SI91X_MCU_COMMON_FLASH_MODE=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_BASE_VER=1
    SLI_SI91X_MCU_CONFIG_RADIO_BOARD_VER2=1
    SL_BOARD_NAME="BRD4002A"
    SL_BOARD_REV="A07"
    SL_NET_COMPONENT_INCLUDED=1
    __STATIC_INLINE=static inline
    CLOCK_ROMDRIVER_PRESENT=1
    ULPSS_CLOCK_ROMDRIVER_PRESENT=1
    SL_SI91X_BOARD_INIT=1
    SRAM_BASE=0x0cUL
    SRAM_SIZE=0x2fc00UL
    SLI_SI91X_MCU_ENABLE_IPMU_APIS=1
    CRC_ROMDRIVER_PRESENT=1
    SL_SI91X_SI917_RAM_MEM_CONFIG=1
    DEBUG_ENABLE=1
    DEBUG_UART=1
    ENABLE_DEBUG_MODULE=1
    FLASH_PAGE_SIZE=4096
    SLI_SI91X_OFFLOAD_NETWORK_STACK=1
    SI917=1
    SLI_SI91X_ENABLE_OS=1
    SLI_SI91X_MCU_INTERFACE=1
    TA_DEEP_SLEEP_COMMON_FLASH=1
    PLL_ROMDRIVER_PRESENT=1
    SL_WIFI_COMPONENT_INCLUDED=1
    configNUM_SDK_THREAD_LOCAL_STORAGE_POINTERS=2
    SL_COMPONENT_CATALOG_PRESENT=1
    RTT_USE_ASM=0
    SEGGER_RTT_SECTION="SEGGER_RTT"
    SL_CODE_COMPONENT_CORE=core
)

target_link_libraries(slc_generator PUBLIC
    "-Wl,--start-group"
    "gcc"
    "nosys"
    "stdc++"
    "c"
    "m"
   "${SDK_PATH}/platform/emdrv/nvm3/lib/libnvm3_CM4_gcc.a"
    "-Wl,--end-group"
)
target_compile_options(slc_generator PUBLIC
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:-mthumb>
    $<$<COMPILE_LANGUAGE:C>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:C>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:C>:-Wall>
    $<$<COMPILE_LANGUAGE:C>:-Wextra>
    $<$<COMPILE_LANGUAGE:C>:-Og>
    $<$<COMPILE_LANGUAGE:C>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:C>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:C>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:C>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:C>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:C>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:C>:-g>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:-mthumb>
    $<$<COMPILE_LANGUAGE:CXX>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:CXX>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-rtti>
    $<$<COMPILE_LANGUAGE:CXX>:-fno-exceptions>
    $<$<COMPILE_LANGUAGE:CXX>:-Wall>
    $<$<COMPILE_LANGUAGE:CXX>:-Wextra>
    $<$<COMPILE_LANGUAGE:CXX>:-Og>
    $<$<COMPILE_LANGUAGE:CXX>:-fdata-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-ffunction-sections>
    $<$<COMPILE_LANGUAGE:CXX>:-fomit-frame-pointer>
    $<$<COMPILE_LANGUAGE:CXX>:-Wno-unused-parameter>
    $<$<COMPILE_LANGUAGE:CXX>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:CXX>:--specs=nano.specs>
    $<$<COMPILE_LANGUAGE:CXX>:-g>
    $<$<COMPILE_LANGUAGE:ASM>:-mcpu=cortex-m4>
    $<$<COMPILE_LANGUAGE:ASM>:-mthumb>
    $<$<COMPILE_LANGUAGE:ASM>:-mfpu=fpv4-sp-d16>
    $<$<COMPILE_LANGUAGE:ASM>:-mfloat-abi=softfp>
    $<$<COMPILE_LANGUAGE:ASM>:-x assembler-with-cpp>
)
set_property(TARGET slc_generator PROPERTY C_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_STANDARD 17)
set_property(TARGET slc_generator PROPERTY CXX_EXTENSIONS OFF)

target_link_options(slc_generator INTERFACE
    -mcpu=cortex-m4
    -mthumb
    -mfpu=fpv4-sp-d16
    -mfloat-abi=softfp
    -T${CMAKE_CURRENT_LIST_DIR}/../autogen/linkerfile_SoC.ld
    --specs=nano.specs
    -Xlinker -Map=$<TARGET_FILE_DIR:generator>/generator.map
    -u _printf_float
    -Wl,--gc-sections
    -Wl,--no-warn-rwx-segments
)

# BEGIN_SIMPLICITY_STUDIO_METADATA=eJztfQtz3DaW7l9Jqba2du+0mpLs2I5vMlNyq+1oR69St5PJXW+x2CS6myu+wocemZr/fgHw0SQIkiAJENDsZndkiSTO+b6DN3Bw8Peju/vb/1gu1vr97e366OPR378d3S+vzteXvyz18qtvRx+/Hc3n347+cTQr0qxuv94vliuY7Me/PLvOd48gjGzf++nb0en85NvRd8Azfcv2dvDB1/Xn4w/fjv7y52/ej0Ho/zcw4+9gEi/66PoWcOAX+zgOPmra09PTPLIdYxPNTd/VokhbxYll+3Ng+iGAQmHqAITxy8qE/8J0mbRvR1D0d9/9uPUdC4TfeYaLXpq+t7V32Tv01nZA/m61/PJlea/fr9f6An4230PhSWjDN+irj9ovvpO4INLuQeQnoQl/i2Ij2muuEccg1DZOAjSo/NFGnLUoCQI/jLXI/uH0vZbq1SgqNBqUyNE9EOsW2BqJE+uPBpQdiQDUqIgK63MIwP36drXAiUXgqWugArlfL/UL8GibQIeJRQCpa2jKqI1vhJaeJktCI4YiBeVUg6ZOYHHoO6Ih5TqoYALby2CLgFGV3mQN1FoIBFHXQAXiPbpvitomDk2DmibboLTPOtRiPsDf/xBspxZtVIDAdexNal0LbJKdQHQtqlJoP2ppf0LrW4wk9nfAo3cuju09gBA90Vf+Yu5YHMFnijWKjsbWc+G7ge8BL+bbreRQ6iqa62X2lW4aseH4fPM1x9OkqAkVeEQf7g3PckAoClFNCRsacwo0ZjMa24/iEBhu9q2YAtSghxmTICPR9HRisj07hj+gQs+cwFx1dVSEczM08/YN/ioAVE1Ddxv6ZEdwXO95cAD/Ro+sB/3N/A2aOhQEiNF83sIUX9S+sfAgrvS+9kU6u6h8QfkG9lnEJ7WPXDOpfULBHALKV/Xv9nZA/a6ODZmW+mHtU/vu+qsOs23XmICexPLjZh1polLJgpM+PXqJYuBmuY+H0ENKWLy34fAyMOD0TkuzSXuytzYqGdoh87U0j/MvcF5pMDM0ZGsNGVKDNtIK8lrBSWuEqrGStQM30Y3AHtbkCCdYgddMqlIn+7+utHypOTFI+TYh0TSZoEohhsqTQBkOJBwmEqhoB5Eewh5hm3imfBoUQMxELACCyIE/9MhXhEoNEp1Ma9Uh21qvrSUnTALC0B82NOVmCohXq0Bhys+NEQE9fgkGDoW4oq9iYYJvwdmDKvCrWJjg369On+F/8rGXgDA3A6YZoHmcO3CJjXvBr+IZ1CwrwYMAxEykMnRSg0oNEhMZmCJVIZ9EBQoreFUqRQUKK3gjikAYKwH+AKVPZVap/FfgsI12y0Nk6RxINGwU8JKyKjWYRNODgvsYqII/g9J7VNv2qnUztvXb9kUOokp6kCWcCNt+aMc2KCqEtGlDtvWRTRya0Q2aQVCGSAlsxKQ3SinpBkgNTBkzUgFOzcho1PrUCdR7CqgTeD9LYhVAtEpz5wwMW9NY3TP0N8i/A8owHSMEKlDqBDjx0kBqXnm1BBsmH5AUYPj1JM0viLX/0EYuSEzL7W5kR3qagK32La5XlyvWhfeLNsGU7y8900ks+kbBIUkp21MFaM9V0jwgs7VWNqSGbaSl2LSMk1aDyrzWnqc8v3kdDFOcfekt1z+/CnoZzgH09OvzxWuhmGMdQvPu599eDc0Ma1+anx0I/lWQLJD2pXh59joKa4azL73rxeWroJfh7Evv5vzm4lXwy4H2Jbg6fx35l+HsTe/uldC7G0Tv6+r8fv0qCBZI+1P89EoIfhpI73U0MDnQAQRfx4A0ByrGzYV9GU7NuRjjtKvCZKnSQH3ZOhKv4P6iUq/xpbVrqOBWaajZOpysoFZpBNk6SqyghhMe/er85sP7t2fnysAnQTHwUGn81zrGq6JWqIKy18+vF9fqlJUcDAtupUaZHSNJArk6g8fWAWK9nEjYmGguJ82bEPVyogzwHM24LbXQd3st7PfaakHCTedBii9gbrQDwWLTpQyL2ZMFJwqluKR1UQn7+aWhNGAX2L6CXApc7B5Ghvlge1I29Fq4lFD1K2FSPL26Clg/ny+cj9skkuJs1FW+cly92GxtV0EuGapeTHaB5RoKcilw9WIT+E9w0h4ZjyoWtSq4fryeVCxvGapeTH6PAltBKjmsXlxC5XqZEqpeTGJj4wBd4mGHDk41fAPYSfPYZeLWz4O3SGu7Aw/cC+aU4+rFJlGzK0qG9EQokf4UGkGgZAaR8Ppxc4IoQhMmFYmVsQn0xoZ2s4M9CA0nQ0H3mxvuhWo6vvmgJ4FlxFK8NnM714liJ04SHvuhtFDKidQOOiVkzEzSqamaXApszGxwK6cmmRxaLy5F66YupzJEdm4RRKUqqRzbhB7clYZIYn9EMQvql0h4vdpJ9eiUkPVsJ9Xk0m950Uie9RBsQQg8E+iP/riodGLZtWJlzjvDUrUUZsh6HIaXuu7QVp/MfksPSKsRGrGceBYshCoA2XlJXepu49NvudscGCVwCiL9trgsQ9XanyFj74Nkbz+09UG9tyCAt0fR6izZ+xBtpAiIzNzUpdSXifStlRYu/bdXdpIX7tvI9F28t89UbdcyZD2YqNrXZMjYmag6mrH7jWL8wHClRKVgoFJgY3emkLvx2MKl7+bj70DV5itDxs5E3Za49zYqSoCCcMaqLhBUAbJvk8jdGm4h1Ht7WOFRTNh7FBNZti/1AG4LmwJbDzYuULV9LrCxs1F2lTDq6YIYubayhSyDxs5F2c6mb18TKUylN5eXKIxVncQcwPXko++BYUFJSvMqg2Tmhx1iVOV1ANdvt1hNNr3ddVRx1engNMhdJ92RVZRUjo2ZzaNhKcolQ8bM5CkJpfoitlDJofULNue+1QMV27c6QIFOYREIa9enNH6Mbh1jDYjW5jXWlCNpYDl9iwL56LYXb2U6jWSWwVetVYMAUmG2xCSgcsU3uO1h1mMxahKtY2ysYV33hzB7yrCXDYk1t2KySp2lwhxkNT7VGwdbdsAjcAScjdz4Uju3ErmiK8ggse8XR/I90mk8yrjYNyQCN1GNSI6Jff3eGXaXqUAOGSR2CuplQ+9cUOJYGpXJsDNpQehDqJEPkwIvkuuIRKVFwce+4g12sle9aJxKsHpQiaG+oXcsCyVTAsZOR+6SF5VIz4UuKCBQtNIQ0Hqtbelo+qXeAIaAxr5sosIJJxohhuNNtNWGJ0vqIhCNSY5p/FGBXoH98QhK5vywZIr82ESOqdeoTjEOGaRB7aBiVAhoAxoNxQhVgAm/V6DpMXl1cQgcOETrvgLYBa4fvjTcSlDKAtdwHN/UN8l2i3YzJs6DnI+WwtXqaOqGZ72YAYSh57Ncy9DcEtKXgbBgaZbC2qtrZAWgcTGsmtddqpepYW0T94sEfXyTWo6jF2vW0gON64FYRPGBYtGqHAg9w0kvc5FWllKSxIIrFR5DXLdUmI6bzth27PhFEV4UVOx0UqMgg+xCA0299L3hWc70J2RbyLViZKN6yHszBBaaZBqOvN6gqVwS2CZp7igFSFbbl5klW+ynoOJRrNUh14qxJ1XVaAnrt2zTDbpHfRmUAMXWk1XJEVKNAEI1SRNwWVlaA07NS9YM29qh+2SEQE8CWMwbruOq2IBIgauGtFwk4ZMPCnSdWUtNKCuP2WiNyvimcSO9a05nqvJ65HJXfMDCUl+VGBCm8BlGgQ07/3BeukHXLm5D+ObJDyWO2StuIFRcw8tkvA+BYcE2jaVk2rmPUOLEdpoSWNLsUkDXWpANt8zej2LdNROmGSFSzjS2tJ+efzh9r0e+qXtmoCMl0gyYM8yeN2ETMmox9pt00rk1GhzBhk26UYVHzkOQFnJlg5VEmnkrFItFxjo4toFt4Bjx1g9VokOg6sdDzwWrSagCr8+MepMoxqgCi4kJakyLpkApMjVkDHzISuerVIXo4PqUt9RhSx1GdWCTLNpk8XQkXI3VYItSkB/2m7HSkC2xoccvAZjcTbyDSRUYK5t05qAYkwIUIwv3rWIMUkCM6H3VSpLfpwQFD3CQunMnd8zo4FCGxcgkiZSrCTkkRgZPdgRQV7U3QguvjUQgTiaP4tHBqRkkK0vH8HKfejlxC7sYUgH2YWeBre0p18OQ0AaMVtUhREHWk4+UMwKMjDrOCZBj1VSTUlxKmMTsyzQMXNtWS6VtcHi11dImszSck/IgMG/6gI4kAwqcPizQaj/mb0tsGwkqJCZ2PpLH3hUe7UNuOn68PllUWzV41DGx87H9GPUED0DeWLbCpYqHnQcO82T6juRZaoVLHRM7HxS6SrEWrAapB5vYiBNVaBRY2PErVKh6lSWsSvI4J0NPQGHeA6M+pjysPao/6D7wTx7zBzHazdRdwzN2tUtVGTaDaF4jGyOyzakc3Irz2VUmZb89Kh4ye5qJwEYOvVODRRkMOwUThDHUahoxnJfHcHCjBBcqKgZScsHXQdIrMMtedbMfnQyK6X40gaI/VdoUjEZ0ks6/iWzJUbC1x6cBtzzZkDMELGDtQHzfzoC4DIMFtgqYewHGOlRAXQXC0pxKxVsHyTL0qTU6m8jKZlXtY5jOxglCsjZTmOSAGFuj0NuaY/ArOz05IgdiSTkLznfw23fykBbq22sBHMWLvd2lAeVBcTs+4YsXTfgaVymq+F4mafJIcC/d7VsiNmZvA7KEFo+Xx3xu4xuh1TabS7GOnMSloZWgJpFjUKygmE6HeUCnTKuAMedBvsACUWF1CFOVaW0tqsWX2dZiEgp3zG9GW8fQNYxAF9VJsG9NcxdO+8yUA7OiuAtl8OTKQVlR3IUykpXlUZ8cz8IiywFK6ObfJeQL8G29AkI7fmEPc572fEZODr/MV2BacIhalUEqJ+SZL8PkasWswDTZUWAVqfIsr5rTcXRV7TTpFKtILcj7LB7hFNPtrzaj7t5PpUIXvrzRjJh5QQPXGhkQxTTwqb9Z66C/1niTJpngVGAKM2+jG87+da/i1BsukothWTYalKZBMwRvuWasskymqtZa0ZpuZEdT+BlVkdbUdqCcogklEDY3m7UhOwDgw8mZ+ManirCmtgPlBMvsBMDGFfWm+j8ZtIaS19X4kX9W24YwR1lqIcjG8rChGBFNZskixhMKN2ZD3OUdyHkA3Lkp4DqKArdWhqd1o9AYCASh/Yi2Tx/AC06K/p2eQAOKVgIQQ7i1gWPBwR9ONCFsmu5msH8kIdA3hhPbLnILnBhuo/ZGwKaBJEwJsqqxGRguLZODq2ntAJiX4knxlZQ2wkPrzSCc2n51rR0AJ7ZfTWkjPCQJH72ZEB2ps9l2WF65S5jUiI3aGQFPnelNyhvhui8WeHywY7KznQhwi/pOyBPblqK2qxBYOyRh4q6xSXcjWGAEU+IrqdOahry1Iew+dsnF3BIDx98J2Pk/4EfatUJJoyH3wHH8Jz90+K+oE1iqmhoBBaH/aEdwbi4iXhkBidTFnrd+vCdcbCskbM8Cz3OkQyAFjEGrqmpkUPmz+ge5ju4Gjm3COR9Sp5+dnL2dv5ufFFzJXYss3EfLTK5z2YthqSj2XZvb2cQqRS2nQK4RFTrbp+Qbm9tEkw1YppBlucqPzjgHdWCDSNPeitcuJQHPsQ6hPKCLSOwo5ncAiwl7J5KuBTgLzuwcI4rSzoPjxj+j6ekAuqwvGXYjgnZrAy/hNgZgM2+usR0XZAH4rT8xtleFzq4SKqE9YGsF8GHNqZGFlE2zmudBHHIcjrAhO+jswObApmliaLnKLqvx3NVhtRptO6d7u6pz6629X+C0H9fBMY/h1YGEqW2aEnFJZ3f9Rz9i8MwtyBgbQlIzU3swKcKDTpb2YFpouco+W0S1Kri4Xl2u2uYJC5hH7d5Pl57pJJSA0NWlYVx70I6XzTF6e5OlMCsNQdcydFodQKsnRPo5unRnglFZI9yS/la08R9oRxhWI+F9EgVqVTmDVXem8Fllo0Uz3e0ocbPEL3paH5Al1a0Y3SDRjdB9fC8BZEU3h7NH9+vb1Rm3Ngb20NPYBMMmilemvDXrfHRfscnNU7APyJLq/l6RK4yqPQugAnRHmc3vsiAWeikyraqcvy8ZQzyANHyBbnt2xzk6FpfhkjDdg7+KNml+HqekNx9s0KCI8autaRJcTWikK6G2qlA4NHe2D0eVwHDHF5Bc0lQFI9eXl4qy/s6TI9m3ehgLHyh34c0xiCnBhVUmKrkFy9yxraS/V65Ixptj4FDF0nsyx1ewVA5uAaYqs6nKYpJXBcBwWAd9/gBCD3C7RHYQ4gMEMZWsbJiJym3G83A2qQygX87IRHyAwH+EBFwrfGwbH1H2JftnP0DbFqJtiKmU1zkLrRzaJ+/RfTM2zgIUgaLOGokjvAaktkAa0+gAhOr2SAbwYwn4mHDpO+CBUPwYk2a/kupunHtDeJtBw5ipZcKnbx2oXRLKg/JurI4vfu5Ng5nrHXDKsmukUq6QeYRtx/YexO+RlIii/r8dCGPeSICc6+2fN469ac8b+AFWsbh+ixcfjcnYQc0aRbuIXp+0Qr99PjgoMTnG1Gs2DbIIyvOSQq7n63K5wlsXRASPSVyWvfTsq+l6OwJeU1837jwTOiTV7ABXwttWMrchAGHsd8R8wWu7lGrOsjzauEYtprQjq1Q+yxmmC9T5UmkFRq1dboizyrYkTxDO9Qtcl+/inK9+k1AoEWapyN3A90WNv3pjL8Aw5RpLF5ZOCLuKd+CHsbFx6Pld+fLLYsFyNeL5/TXqlj6z3JOFlE9eYVK7aDlxDfLSctBajojhIgn0qWuYIbdYWvwYFLCE3CVxDdxrg+WO1j0wAv2N9AzO8GoHOONiUNOGDyxNplDH605zZCC1JlfsGlxYhBIULlA24DKODsgWCEKATplY6cU9OC6BKKc5ZgLNqDrogEd0imsH+QfSSZBYOqB/hmLQJq5s2GUcHZAFun4yw6X7gtagQkSRsQP6JtluhXldMYOuo+mCHyTpFRlcQ0MMhl9DwwD/KTSCAIRKgC9j6YCe94myYZdxdEEO/f+GzaZ0S5dxdED+PQGJdBMXIDrARsAN9tLbkAOKLrgxioeGB7jSiwSJpQP6Cn1+rQRyAkqnzfE+vhq9TQ1MB3jk0S8bc46hCyq6xlB62TigYF5Aos0aJM36yvpbNyYqA1pJYEkMrYAFHkXoBEo7k9DQ7UlCWChv99ioNB6SoNZAtJ8BgG2HtAJaKG+HmLYYsjAW2nl4mIFd931f2OHm0QZPnXsHyy9flvdd60LpV/r9ej2VCVOW2oGIlmLQqlC6xjP446m6qw7MLOOvAzk1MOdQuoZfDnKhzNoLPYtRIZlAA6ahmxe9tgyJiBvlFdYgmJtBMMA2RfQSDW9qGrEfaoU0ra7JNWyPo6qDOIouFPn6PUdlJXkUbecwMTr4C9P8dWDURPBswGIFXx08F9PidkBT19IJ5XoDrIFW6A3ooIsC6y5PtNgb3lC3TwZIND0McHDjLcpMjcragC095GM5bObYB1NJDwsc8UaqaGqDdJ3e/yXcQiU9LHDEW6iiqQ3SXRZfXLiJyopYAP1yOoGZSGVMwM6mBHbWDWwFOx+Y2cJzsKSHAc6XEd5TA1B9IX2m2m0lPgcrmhggLZIo9t3pgJX1McD7jD2GJ0NXUkcB98mIwLth582RPyP2a0wCtFmiHUQ16xnGukFTI6cXOFBa+z8PnITUtFXEtevjxI8QSNG5+Pny7srf7YbGKSJVOqksjZBL0bwGz/Gt57zkX/GhnOunSqegWOFiv8C3nQ02AFmJSKFdeodTb9XcxHm8xUm1XVZGFe3Nh3SMONjKEYiTAM7WXxzfsDRSZJfW4WRb9LbVqrvMRtfA9cNhs0uycNPF0ubRLxG6UAnFuU82Ee8+giadAsIA4xdKXTg7jZ1IC0HgI1OERviiZYJpKiPvFCaMxq/N0xWXxTeofwrtWKD6QjxF/SbrzkToPsimKbZ3KL6hGMWFbIpi0xSkNRNMU2kHew4bKnSthexGxdgFRqT2QgENQnZnj442IgSBIFXQYMShboWb8YHU6AhK0inKgWntxSjOJdOVRoYwraloqlpBRS0TTFepm0n4KKrvqMqnAfDi0A/GX5VG134QTlG9f7C2YvTmkmlKXcMUWJsq4mm7C+Mvmabqda0Ghfh6JREaM8E0lQ9m9L0gpblomtps2CZIc0k6bQS6N86+fydG9UE2XfH3p+PPpjUpzmRTFD9/f/KDGLW55AaluhkCQ9SYk1BAbbG5hfVKX+v5dCf7OscV296LGb4EaUivTC0dkM6hjx6GSW/pw+FLDr34UFzNvXwY+tw8hHrByhVTQPn2+I5hAKRMLbURl4EneGiEw2cmMAhT2xwheOAzAR8ErG1yHjzwmZoPAtY2bc97UnxpphR4JIDmjoabW2YffGXdDdCwfXUzktKO1QDQhiUxlJ4EeUiR+9XpM/xPLNrsHnn76fmH0/fap/uLt2/efDgvVhPx2mYjrIZVzQVi7d+dX62hCfAfXFevf8VQ2xRRcN0vzy+ul3PX4uQ1VJKXaTPxgnoSYqeZXO1FGiUGKoXggVN5svGN0Fr4bgBTbPBVuGiZLLRQDhgfT+bo/85Pzr5Dj05Ozg6P3sHEKGvJtK6ZzA042n7aunOYoztoJvf09NTdxRsUjyX2fcfcG7ZHpoPvIuuBfAqze57afA7fzvHpDvgA/v4xv7lprh+/eXd2+vbNuzeHQF8/ur4FnI8WiMzQDpAx/vyjVn+Wuq5VjAaf/YgPFgEzhr8fzY5Wl9d3V5eLy/Vv+mr99eLyVr++vfh6tVwdfTz6z7+j235d/xHAPPi4NZwIzKD9EtuBNW/5jL33I/jmP//r8DiNC4Gf4pUqqLs4E3nYipkV7+7XS/0ijY+KnMQq7w5OizpKWn2Jo4OkYUEssEl2ukmRTsQRqn8Q2B71ObqpCRUevWK+5m/iMHXgqLzNriWgSvdAXAB7NGAdiGqf4IZDT8/8RPYfZVHI4DDDExRG4eO3ox+zLP14fY0ffvfsOl70MXv607dv6D67OPioaU9PT3mRg6VPiyK0wYw+mgOEFn35XZaTOFkcJulD28J/J+Y81TvH+zHzxMwytai3851p4hSB5VZE/PkbLpD41Aeq6hGsYagFSBXN/w/6qaGPihKa0/kzNkwGCxJGEv8xG1s4jST2IWpcAhfFDdpZLuQv06BTqCHTV/5i7liVt+nlOGlK3TRiw/F3hAB06xA+dLE3PMtJl5XbXtdSF1FN0y+iuoDaF80ycAhiG6/tmumHCpWkNXBRVwReYVmqe5fOmr1JZ7Q9UfLhvniUu0bMyu4ds7qfwox0lZi1jxVmNbeDWdOW6YzYrZ7RfVIpjwt3zVmTPyTtBSGr4rNHe0F8X/aooz3Pndqo787q7yoeS7QXe+rjsiMR5XXJk4fytuS2NauMrWY0rwXyYZqK6n0xK7aEZyX/9RmxazsjtlFn5X3NWXmvcVbs/83K23Kz2lbZjLJzNatuI82KdaxZeQFpVlm2mR12f2alPZlZsVEyI/cvZpX9hFlprWV2WO6fEYvws7LP/SxfIp8VayKzYhF7li9LzCoLArPSkvOsMiOfVabBs+oa8YwyFZ2VV3Jn5dXVWcVbf9Z4A2jPK21GCcquRhklo3RhzVA5pRtQBoqo3E8yUEb1Uht2IS2XggwVUrq0o6+ILNpb9WIMFiFNtxwOSFuEEeqfNrt0tX9C2lWoA6TQb8ccImgMiBAMS5nfmtk/ZXHV4ICkxVWAQ9KGhxFNv7SdF8gOkTg6+2sX8fVPS16R119CcU/cgKTF7Xe903bel8gisTkGO3vqWlTwgUnLAc+HithVBoeDRGQhuUckP8TKHiokj2TdM31DPOKeUrrDTA8VmAeBZktPCcE7KGH/QkGJYsySsOdFR0NFtlwY1Udk26U2POTkl80MkkW5/oiHnPxaoj6yWi8lGS3ocFfIAFH0K2xGCzrcLNMianhYXZ5Cuwf+Q8I1DxJHiXozRg4ZkGaMLFoIRh7yiNhVPEQyTWYGBSzlIa85figP6WRgTx4yGeYZI6JLcpFaC/rIS2o5GiMPmeVQiVzkleIY8pBXxBnkIewQBpCLNCI+Hx+ZRPg5HkLz+HBcZBXh28ZIY5hcjoywLkZyEfmci/h65PAxYosQZWOE1IKHjRFWhPcaJaSIv9VHCkM4J47i8ohWvEXyQtkQTmnW5iI1o59ohI+f7AiYvucBM36DEb2Zv4Fwir3xSMOOErmDEZobhJGdek9kaseIoDppDBAIjbILbH8sLjQTOzM5SAmeXA5SIi6MYM6H8ShSaPZ1yHWTUQSxCWBZeDBqEAvEfeWk8yBUXWAdGioj28wcisEGAHw4OdPLA8LeMoJRyQcaIJtH56lZszJdyjlEgkNuka6Z4J06zdzbAYaVNzismNikos3rnqZiE2wZsSFEMHCr22Uc5Va2kTjKTT/kLBc1GaYZiAGNhKfOAPzlBlHV94+z7BAOyraJZwqQni2QCUGfOjUKKSmpaPcx4C03NQd+zVE0akXtu+uvaFlgl/5m+TF8FriJbgR2xLFhbdJVy23shMtXL9JhARBEDvyhR74pQH65PvCVng+H09znLLtcsPiIPnTvqdk3Ca8KfOj6D5J5Ys4X50tOz/4GeW5CXaZjFPtTo7Vh9+q8V0lgD8u3oTvIR9tVsMLZfgjHrIBzb5B5iWfZ0aBqrMWs0EaOWNm2QfpX5hd0kf6Rb1Wkf+qL85vR/Por5TMy6K13uf5ZilL9+nwhR/Hdz79Nr/hzyc1gQrWXZxKMfL24nF7pzfnNxfRaV+cSqK7uJCj9ujq/X8tQ+0mKUgllCWoV1BRP0MUshTXnX4QVd2GNo7AGEHZd+tX5zYf3b8/OxWgQ1qAJy8WvF9fnYsaIWLIYzLgxFQNaXDvNsy0OQIgP1hiOnj9C8z0jedZDsAUh8EygP/rkgVdhik3k76gngYWO7gnWheY6hjV+zYtBjWnak6hBZ8LTw45TaAunsd34RWsmLePX3BnUWMYkNgPbJJqk/gC0xzmJIm+Pjhlb+tZ2p9A3kZpdYLnGJIqiYJImyD6bpIDbZ5NUV3uShtQPDHf8PgODouBpkkL9O5ikqP0+UZFGelJ3yym0hZ7wQRZWM1XDE1m2z2/FrVWRCyYp3tE0PV7k2tPYbZpaFE2lB/sWTadJ3wPDOvisCtVY8Y4VqimZqHVAenKn80n0RQYHJxgGRY8Gu2fbCDVPSTjejaBDT7GR6r7VA6GlD+1AVlYAeC3NNOjKZ7ETqEknShMowjV3Ij1FzZ1CH665vBSFvpsvpxWDY8N8sDkOvigq0CPTeeBXh5p0cFyZaVLBrxVt0MB3DaNJCdf1iwYlPNcSGlTwXUdoUBL4TygiqfEoPFt4TlQbVHCdPTbo4DmXa1CBj/rovPycmZTx8V3sUoWGuqKVcB3ltujgPsJt0uUEUYR6GG6K8kPvRayNYjCYetqlcTt024u3YnRWPPnqOnmNB5p1EhFKuCnE7poOeEwPP2aHWfjNGWjyrYhztaIpQR7HQhUEjiNWvmj8/HtRqprQN0EU+VAV8CKOO4I0ZSHYcV1HouuIYdo+Z/IGaeG4dkSTDx8EU+QIqug6mk4JblMEdDkULU9PFr/5RllBPrvErZaItr04VOA4QuWXy5VIPYf8HqPlyQ6BA1snzdhvUEcOwq0Bvyn5MYz1kOvQwOmkXZcWbEiRGoqQpEKk+0KtEzzEurtzx1XsDh3oSIZI+UgorDJwgBhaT0YIJ0c4/rhIjY7h5QNhDj5ZLNpw3B5xNaUIzCZOAdq0w1em4CNjE6gZP85uUJS3w2hGggqe+xYdVhPRGNM0+cI0oQgF1cDVIlXo+WcCdaXTx00iXkda2IRpqVYeLmpAGHp+etIb/canoqRCK5ZJpXOBvLVDF7fwSbALDRRQr/ogDRcyoSouNtv7UYxqd/a8lNG6ZwY6es2Hk226QX5VTXCI38tbKhejZJ0SHj/0DGrBIjdfy+ob8aOPbFRWMHSbV79dUcBzYFsRjMtj0QAJUGD7MSrdD4DTsLMiPMju/eA5s6goQJ5oIgtOzzg47IL5G+TJ3tpcx40uvqFGcw3Hga1fGsyKU9+dtlA5ctRYcW9b6irGb9N0CccVdZcGyiLunOKjMOvLSYPxzJOSimZOAhRmmwtQrRkCCy1sGg7f0lZThJvVLNqVyWn9JlPCP3cq2z6wSm5QDIctnOqAJz/kC77SpXERHO9DYFhwPJKNnrHzVOLEdvoCsEcsy3sUDTV35aaPuZ41SqCZlYPQ3r1Ts6yBg4Fmgf16oaqcbICcWX9Y/mUFrsn6rELzzcpNZGVjGcwS1nFrw8yuWYgN//cO2v0dJ1lQ1FhJEaxXPTyOmqT0G/c1SXlhL0INIpIePkfFzjSIUSHR3fSaulJnzFHUgOrLINTyuIrrHaeQQSZ3gQPamyapRctzGNX1bSlqIotRD0dR+saIbFM3QRindxMBONLwe8RaYlcxYMjELBw22eiK1g7JYXEBdYlvpBlPaHPMBugK18PzOb7cr8vxvFtkAMcoyKwP4AWLfAAds4cWkSgW2dYGjgV7IixskKA/khBAu8GhjYvvhBouyjTQn8OTYwtxEJHbdogEYASD07ovcEj5YMdksRkjawwXVF9AOMqgqYhRIPDwulyjOIniAMraoadjijzqI/AGZQ8B+9h1tD1wHB+2Yk6HbweRzPF3XUMxIkWQXyTbubZ6SOjHe9wV4ijgUEiW7vn7kx+yJhX9itrwwwmP7Elc+hNfaaqbEZ6SKXOxdNGhrPCfr+1yaWXsuMAb2JmMOzjP+wQTW/9rz6H2zO6dg6USpthF/2vIoYZ89UXy25GRxD5ErcERp1kE7wxVakUTM08/uXX/62h2tLq8vru6XFyuf9NX668Xl7f63cX16ujj0Y9/gSb49u075P0GVf307eh0fvLtCD4B6DJ5WLPgo6/rz8cfvh39BeqESjOd8BPPcMFPNK6LNAuqVJFQmDaA44GXlQn/hUlzWUdYNPwA/v+PW9+xQHiQn2Zo5Zv8SzhrOXx3uOdDRwBQLwxfZiAAzJfUwughvqUSPcGFLTVnq+x8Xp9ddvloOEk6z+WmIb92bVF4OHETfb9e6hd49RbHp+Zsl4Y7RISoiEPf4So8sMs+ZTwxZzcGcxdNXLoqAnqxM2o+wN//EEID35+aGgkHwx6p40ctbTXKj+w0yuWdEe/hn0loI3ZxYtn+x7zh1PK2JZVVNKj4r+/ENI5r4CKnLMCrecw6v+72Mb2aFz3TV/5i7lhYZ9GLHQxdtz5TE7Molp6yXOQjOr24PZUM556xASd1vBWklyqWNnTFCTf5Ci8urU3lczd9Tb4o/PiKYhuvxZvDaQxtB4pKNFlD0DqvHtwY0NcqqG1DbZSV117K1w1p0i3hxu8bUqXj6o5UjWlh18SUtEGAayY9kjfaKuxizS5rbwcDZTXZCM18RghsEFtcgMJBeJsKdLMKNxW5okqz03hty7e8eUDff9R+8Z3EBZF2X6z0wdYp2msuno5pGzgHqF4XmLpG4I0wWPdYDh6NuGOm3rpyNFHlFh0VzVIByMsUlN5DtiCiwySuvJGdMySe8RlBEibvD5LOmATEnTLlQibZpCmQhNCu3XOlAvEaqDHUOTQM9V7T49Pf17KjuNpPZjYU4ZBzMNxLXvVyS9lcq2i4k60eA5ZNtoqGO9lSkCDZTEtQhDSd1Ts+ZbOtIxLeTSrCmoAkhHbtglEViNdAcadeuSJXNuUKGBFU1anMFTAiqB4ualaA6gGMqCZLrXpbAcR//kZc/iubMYmHP+H0aI0y7RSJRxDh7NpoNdhmYKTN08YlZnZ/GCGT1xJxrXlrvklXVtFgvelX+qyeOqQnLliWa8QGUKMsx1yElGDfjG2YEXi3FGiU9kpaiuIKdGm5Sr+RnX8H2XUru3wDdEKU3jhOteSZFgOZbQ3OlCKcXg7ntY1lhiareRikgRm5bbaXbhXl207i+5VFbLtfjAfbKv8y9Y4Ru+OekijdA/1t8uqVh/hkvhV7wXHNg8E05zevxS4p0imMslz//EqMkiGdyCh6duf56zBMjnYq49z9/NsrMk6GdgrjfMbx/F+HaQqsUxjm8uy1VKcM6RRGuV5cvhKjZEinMMrN+c3FK7FKDnUKs6zOX0tZyZBOYpS7V2OUu8mM8nV1fr9+JWYpsE5jmE+vxiyfJjTKa2luc6gTmeW1TIxyqP+MLtr8t31UXSfhuiRCcF6qNZldcpitEgy/qDUS+MKhuycYqjWB4jBJIvipNRfiMN8h+N39/Jt+dX7z4f3bs3OFiJKwODJWa8bCYVZC8lOqyeHf4ny9uFappOZweDJUbKbEZTZU46jSpIfDxIZWSqVs8TeX0rHb+bRSqhDFHI8KDjmHS4v5bjYLc3/A99w7D5LOBuUZ2nDXcw5MiF82VhBKOkbSRTwUd5YEyQe7IA3PrRzzApkYX3zDfMjCfCrFvIRLXFmXdN6iq6iLO3mBy9M2iSS55XeV9ByZMO5b21WSeYZLGO9dYLmGkswLZMK4V29eV84AVXjirPCkZsnPcAnj/Xt2Qb1yxHNgwpiHCvbqJVzCeMfGxgG61GPvHRaoIRRsC4knD5ksIe4kYqEnv5hZPQvkyIRxT1Tt+hPRPT9SoD+FRhAomvkkQHGWcIII3YLxoKYZyuhe2ymP3O7E8hTMUTvYg9BwMsZDz280yBdyJs10fPNBTwIru6NDXkmpmw8f0iIBigkjE0qKu9VBvoRNCO90oUlV5gU6IdxxX6Qq9RycMOZFH6SyBcogxVgiMtK7iNQ0QY7uf8Q51EpDL3XMQskSNHYhAQrriVQkX8ImsCdSlbm4DRkjedZDsAUh8EygP/rk7RZq2aIVrZByYVjq1ocMm6DAhpLXMNvaAVPcMiZCaKQ3AihLvwJRjBUkb1O2sRe3VWnGkj0wWmmLc8KwDHXbuAybmD5f/rZ0W58vdGsaeHt044slf3+6zQQESCGWUNkAInkrsEHfwlzsJv1O+hZtG3WR27T2mbptfYZNEG91+/YMmxje6o5jbXHjVz8wXEmRURmIF+jEuFfKdrtpYS7S9eZ3oG6TnmETw1vlvkyoyxESji6oitVduKtCFLPZLtvpqoW+UMcrpcevodDxa2TZvuSQUi3cC3SCuLtA3R6uQCeGu8J7FJHAIyORaytc3DNwYpgr3LmL7NsjpYkLZf4ShbG6k/QDPIHs9T0wLKhVcSuUYQqxBnbVVdcKB3jiPKRU5S7UlVgdN+IOCwh3JU59kJQ1QY5OCPdHw1KWeYZNCO+nJJR8dqSFeA5O3IUV7ls9ULPNr0P8J3Gdj0CIDMLXX957dN+IuJqAjx9+exlML8TQtygctG578Vauk2qWPxoyafXqFCpQblEPG6yDYOh7WDmwWlVNU0fJoc3iFgdSjE9v31IttZWtZF2lfaUCVSL3VGq08aWSDngEziuJ87PxJQ/oSiYrBjQZKDGeZZEK52BprMvIxGy8B26iHu0clZidZ8dRj3EGSgxhFbNYaA4rEtiEylt8VJMg9CGtyIdqgBfJdhGnGoGCUMzuK9jJ35ugWaAETBDxGGKzZccJp1MvQRNDXvbGBJW2wO0IqCxQtrIT4ITtQOhoOUjFoSsBTswCtBpxLGj0uQWxaCT/9GRJXnyn8c5RqXYsWdilzXjULneVqZQN+fHwHJWwuYRyjDNQwnsa5YgT4AQ3tMrRr0B7rVseVYOXQmTLs3UpOFN/u/Y2R/8EZAP/ZIfAgdOr3q18TZILXD98GXy/diUvXcNxfFPfJNst8saYvPbkVtFSUlodj/CsbbAyCEPP53WJ+djevWlTAoOUmGtYf3XnqICkQjT/savxhN1TbpOPaQlzo6FsgWRSK/OqW7CweCBWvXJBiGj/DISeAR/FhilhdFFkfWoyYpOWCpDjTSGpUh0PY2LbseMXZSxAwcWfeGpmZOJdaKDFMX1veJYjI/JYixlaUfI1yqHcmSGw0IKh4cgcNTTVCgLdP2FXRKkC8vqlLBsyNwQKrimrpkpmaEUpyCjqGeDVjlNs0w34zLMycwTojhh5zSXioxFQBmZMMz15xa9Gb0C541V0tnboPhkh0JMAVn1rqHsoYWdCKm5SJJYnkiT5oMDHpZBRhcsrbWzkJRbB4fOipoFfut4mc7xXHugd0PBqwxSZ6KQkucxuGr1ZDcfZwAmjvg3hmyc/lDq3rThlU5HJqkPxPgSGBfsSXjXJzk9BJE5sp9KBJdH2BUGtBZss6+/9KNZdM+G2UoTocZ2F2U/PP5y+1yPf1D0z0BFgiZmZ2yt73oTuVY7Fjf0mXezaGoMP24heOkRNNjo0AbMAHXOCDZjEwlAxWLEdWYfHdxoaOEa89UO1iBO4xDDWcwCqUq8AFLEuuEmU414BxpUz6iyL5lUx2jVsHJmTjYivVlWnwxNR2tMjICpxr0P7J1z4zqKYu1Ln/lXbl4Kru+MdqKlBtmNDj18CIOFodwfnKjTevNMZvnKcC1ic+bpvleOaQuLM01evHPsiym/wAKdjO1eCG3QH2zIwzpyTSMEam4PizPXJjgAaaOyN0MIrvxGIEwmxgzvYN8PkbQ/H8PLz57JuAuqyBRWiCDtYYGt7CvbYJDiBsyKVqFOwCWIu6dQ6I3cuJ9frc6IUkWKsS6he5Zrn8KlT+96WxC16r7a3NTxzGiO1eBC8J+NCJpInBRBvrmi/GVvSltrXEIRJVHxZS58XVtiOnQ42scS7OUWTpgrbOiq+rG0/Rv3zA5A5a6owriLiyxaH9zd9R/rqToVxHRVf1uhiA+Va6RoozpxjI07UIVug4ctSqWLMvfRiONJHuhlHAoxKRyCZPu34qOv1sDCc9UCbIEY+RrpreMYOnWhloTfOjYDuO7sxItuc7lhFET+wyr98roSKiL2YtdGEHQx6qwrHMhw+BE0QxhCRacQAtrVwOKwIUyqukZRlU2Ol0KcBG+s51nY+Q465Uo8wAodos/VbwKAbbaKBYpPhSodZBo4O6bQsTz6hDMNYKnYwxbiPgU8ZyFhSajDiRgfrV4NTFcrYzkcyG1YKPIbEDY3sJrKy9Ylho9dRjTQ0gbWZJhMOPLH9C82DSxCUYKdn6GURKKkfy+IdlPNOJo8CwPAaDee35kQ1muBwUD0c/QSLlk3oB6xOkuhfJuoYSOgv43qBRPSthg24E/YbC2Wshmx8I7T6roWkVpCwBJKGkoeIxc6NsIpiUS3MQ9hnepWeCx2QCi3sFQsdgvxnegdX0kJK5nKThBMc3m3mUkcxZhC6C2xfSt7UdI9hYZ+ZskhUVI/hEDy5sjhUVI/hEMkrTBGvspRdcCmLBqFd1S4632Tt20sjO8jZpsA5MPXJ8dxM+GW+6tuCRP2VYAR+UpvlS7+5YqVHOi25K7QpqdqsvMdKRzKmgUzFTrOu3cKL13I2ljalt1IzpzHeSQ3EJlg0bebDZZkU13s5BFTugNNTAL0nyYydaD0bJoksk5LK+0nm+DHDVp5ZG/q6LQzLstHkKw1cKtwxKrNKVjCpyplKaY2H6UZ2NI1fdZVDTfFA/NN0QgT2vh0PZboKAPhwcjZF41zFXlM8EP8kW6YE9J67o80t2ISgmUv40M6h+QXZ2oU5t8Y2r97FHNxtutZVCWsbT+jSCBtapOyzMw+AOzeFXGpfsNPKoLVuHB3Z0kgrCO1H5Ib0AF6wOPSvDFoNOHrTgrjCrQ0cC04YsKBJydC096PwRxICfWM4se2i4xuTk2jU34uGaSCp00Kv6uwHF5dBCZBregfAzmvMxKhLanuBRjt5IJze1nW9A2BPbuua2l6gkXR86H5SzKTWfnbGOsqd3cQGb9Q/gsb0xaZJfS8S7osFHh/smBxyTEajBcAgIpPnA0XxkGJk7ZDUyQcDTdp7UQBGMC3qksImoH3XqPax271BVGHt+Dsh/mwHzgiTVqjplSV74Dj+kx86IvYFCYRVXb1gBqH/aEe274mJZ08AJbXxKjt+vO880EQQtz0LPM8RKqG0MTKtqqw3a8oL2qP6/p0bOLZpxy8IlH52cvZ2/m5+QrFTfcc2C6TZY/4/aIl5xLJq7Lt2Ne5KFCeW7X/UUA7kBMj10CLVsGWhjR33VZklGbPo6kdntECADMpp6QchsUuiwHOsw+rwgC6Rt6OYCE/QjapT1tAFXgvOpR0jitJuinS7YjEXXcRQi40G1ChjmIWAl7h9TZKnGaYR4gZh7ypzSDW0JAyqK+NqCA4F0l9nyLx1S/E+ikOy22bQeUg1UKsDK2pvpXmioUxrO2dMTNm2vIZtCQ7eHm1v/0xGjnn84w5Zo+ptPyylVMNrEPoRg2e3r24y7aga1VP3IdWYGtVXaZ5IzGZRQ6FfXK8uV31HeQuYN8P8+C4900l6XSlFLt/i2oH23GzyxjyqjTE/DQHWMt1aXcRgD5VUFLrUm2ks0AimJGEwlvgPtDsNqwtDW04BUk0+0iI7k2Ek32iNLPVwDLjpICISM0MoJR6MwA0S3Qjdx/eDIFRSSz6heb++XZ1JreuwJ2S1IgZLFKYs+eCs9CM9ts2HYRBKiUV7rq7wAsVwY0Oo0UuE0XZ2XGWqqV6tmlxVv7mBkXbSUEW67dkDzymPdV8vAdA9+Gt3FuVn/0op84EGTZjqftU1zJ3VkWaASmjVqjDJzaztwzEnMJrX54QWr1w7e7HKU+Rlqixh1FmuTI4exgwD6C40uRTVS3dhPeZSXTDOHeRKErjZfzSaXIrkyoU6JiCpaqW6cVvDXp7TRMXEsCpi5PE2JOoBhB5wRuI5CFG9epUNyFymM86Hk3llEfzyYByegxBVR1zAtcLHvuMtpr0nEYUFoOX57jzBpMprk0U6yS2d9+i+kRFJB6pF9zIYicNQw1LroTRpDBYi8fBoMlDQIO2jteo74IGQZVRK415KPA7F3mBoT2gIsoSjtetbx4j2gzEcko9D4vgs83UaiDyl8JO4Y0YV5QqT3wfj2N4Dy15DiTTqzdtFcciFQYDylKJzwbE3w3MBJsZgF9dv8YKl0YMpTKtR0qvbh3dbitduGhzUmGTM2QZzIiuiMlNKotBJwRwVQzuEiOBRhDtm/zhL3acvIhSz90TiTyyhw1Pszkol362+5XQbAhDG/sDYUXiNuVcjMnbZlpr3h6XupnqD7Flxcct5p8vk+TJuRVCP9r93RPbxmwVUQ+SsWncNumyRr96TwnrHqW/A5ga+3zxS642uECckv8Z0sOn0dEz1CPwwNjbOkHJBSPqyWAy+kIoQdX5/jbrtzzzvBkZEB1Te1MJabiYNstRyeFouk+N1aUika5ihP6D4dmItBL/KG8+ugXtteDs+t57tgRHobzgUiAyVdhCo0m0bDaa0+XQGHS7FnUbMYGj9nIxbAMHinaCAs+MhlSWNBGWBIAToFIiVXq2J40s0u+YxQ2yWOxIweETns3bQAgEHmKS0keA+QzVoY3w8sLKkkaBaHTyZAfXx+GwB44IoMnZA3yTbbYsHFzOsuryxAIMkvUasHuZiGMCaPA4An0IjCEDICV5Z2khwec8zHlhZ0lhQof/fsBHiYK2ypJGgfk9AwsFMhZiRcCLgBnsO9fEgZyygGEWuw4NCDhlHShsJboXEXXPCRggbbTe8986rfa2JGwkPebSPR5VLGQsGXSnNIQcPcoQumtBHk4NnCWUJgxf7KwOowVBIKYPhtLred8Jg88FvUZ+2xoP1F8mHexhUqutgIDUxw/3SYU0dUTCK5MMBpHVzOIIivWw/JrAbfs8jdhh5tMHTqNXq5Zcvy/ux8/JUin6/XrNnSspdO9DQUilaVdjYXh0LY+8OOlDxGGcc6PFClQsbO8xwkHtf1kLo2Yn40RAbpMpb2ua41UU9419dsQqCuRkEg+IXFLEYNLyNZ8R+qBXytGadrmF7XJUeBLZoRZG933NVW5LYovccCkHHSGHavw6O2geeDTdw4KuDl14aMOKAq66HGdT1BliDLdMb2kFbC8C7PPFib3ik2yJXcDRNPYDhbkCc6RrVsUBceshLMJzAdiVNfYBNYbiKLhZw1+m9hRNYraSpD7AprFbRxQLuLotqPoHZyqr6QPvldBLTkep6QTybFuIZO8QV7PJgkZggf0uaegD7QvFCEorvC913qct+U+RvRVcPcIskin13SohljT2AfsZ+uxPiLClsgfnJiMC7twOLIPIsxB6GSYA2IrSDsG6NQy3RoLOT5wsc0K39n4kJ2Ai9FYFsmrlxJkS2aF/8fHl35e92w0PdkcqdVJpGSG7BsAbP8a3nvORf8zJDjoQqvwXPCledBb4lcIRRyKpIimVFMMYcrRi67MAjP0gArHmAqu2bD+lId0QeRCBOAj0wXhzfsDRSKKv+MQZoQcBSN+8y+10D1w+HzrXJikEX3LbS8BKha7BQnPlkE/HvpWjyW+AYoLoUzY6gvH7mwll77ERaCAIfmSc0whctE92mPPJOoYAICINQVtAB5Cm0Y6FACgUtQDZZFysGxUF6GwR7h2LyiYJQSG+BYJrC9Gei25TbwZ7YquKpv5DeCQG7wYjFUahoA5PdMaSjjSdhcEglbYDiULfCzU4YlpL8FhjAtPaiIOSy29VHhkD9qfBWAMIKZya6XbluJuGjuN6rqqENiheHfsDjMjo6joP4FhD7B2srCkEuu029a5hC62RFQdvuEY+L76kI3NrV9qRTHxDWaWWi25Q/mNH3wtTnwtsAZMNQYRhK8ttG13vj7Pt3okAcpLdD+P70TCCETHoLhOfvT34QBSCX3aFeN0NgiBtPEypaewqTA4hscpW+1vPJX/Z1jjC2vRczfAnS0GaZ4nZoOpcxxDB0OsMYA37EZZQxFGH3KCQMfR6D9SEAc9Ut8HybR4c0AFymuLXLkIMsqAVTqAHjNfMZhI5lThQ88Fq2GASRZUkjeOC1oDEIIstiR96n46tJJQElIXR3a7EcpGXtHSCx7XUzktQu1iC0DZZiqCUJ8mAv96vTZ/ifaNzIN+sZ/nx6/uH0vfbp/uLtmzcfzos1XbzW3AisY5V5gezg351fraFR8B+cdx1+xaDbVLUgvF+eX1wv567Fzc+tJLGiNzuKcGfEez6auMrPl8+FCCUzjasSHMiGr7ymQsZdT3GQmqPcP/74Q8/KCLCQh+lxHq6Po5Jyy+I56T0U6YREBKWqNtufRlPPlh7HIRIEhTblm0aZCCMTW4aia6+cAtLRpYosLeTteOgqDd8DXhwV0Uo3kaVHvvkApCFJg3wXm7TYWq6ZaFZoo9s2skhH6V9ZQPuL9I/Laer9WNAys9cD8ZMfouO02C9V1TwOfTfPYcUQonBrmrm3A1nANr4RWvkHihknz74AhHjT1HD0/JFiSNNsxB5JCsLKwxOrBC3PyKIlyeKvqoLxyQ4BnFFEaLHR85VEZpsuOeeUD2prh+6TEQI9CXahoU7vebCagjkZObqn1gipgGbsN7rtQZFbA13woA7CSiOCj4864DGNxCADYpCd3cAvJwVBv8ldgvr0ovfJ1WZ3hE+f5b061o5bTYdKqN8aN05S5dqyoaIarlwaKo68ZWG4nCzOcU8BjIFYuUmthpThLZYadnNsTpcv/hmXzT3GgYMCC4xlerh+hZCEI0pdFAEOv1X2JvTVb6v1Etr69ubz5Rf962qpr24Xf12uV3g74NGAzQ789JRV5sXy09cv+vLzNWuC60/Li/XVKgfw+fJqWdH87du//p748f/N1pGO0ZT0uFhzPDbzAx/ZZ6xqb365fqNfQab67S/L+/vLi+Uwvrd368vry/+31NeXN78t7n+7W+vnK2byq8ur808r/e7+9pfL1eXtDfptfbu4vdJ/Oa3gOWGWeKXnFkV5WaAaxg5KO2Bb/Hx+c7O80pc355+ulhccJH5Z3izvz9e398NkHUx+dw8zYX35y3LFbvlfv8DidH16enr9Zf3pnB3/pb66xDshw+hnyT+djBPwN/168TXLCv3z1fnqZ/3T+Wp5oS//tlx8XUPrcpH/t/Xy/ub8Sr+6uNU/397rd6v782sekhe319ewBKTIr2+HVj9SKG5D7s8vLm/1T7fn9xfYKPovy4ElrFM8lHw2uCKkIm7Or6vk04YsXy/v16wVUu+Xv1CEnp+c9ZZ3s1yj3Lq7vVnerPXLm8XV1wtU+9kE6Ppqfb6+XMCEV5c3VaI4xIcJH9ieY3vkeKK528LN9v3t9cU9rPGwTN4vVxAaa/KvV3cr2N2MEwLtkpaL1NqXN5fsSWENwsWy2sA/n5hfr3rJWMFuh5BxtjVPTnqIoTUml3fXX/Xzu0vmpnRxv+BgSNwq6ojXdTEcGTUEwWzGSPh6fj+w28wsmYqBjdvXoUDS5vHu/MuynttvT3541z+jbz9/vro9v0C1+tfb+7+i2rn4K3unWXcBYNCZmeOWvXOulMvLG9gJfT5fLJnHBefQ9Es4tL1CP8s9zYBeni3B3dXVqDrw6+XnyxGtLEtncnJyxrszed9PXjpWv/kKm66Lv+rrn5GfEBqDw/HFCg4CUSm/u8W5XZ18nPUAfLDh4nx9fnX7pW9m3K/XeOSMR/HfhozAixB2+mq5qI3EUpMdPuqdJQs4WCrTvL2v5jjaWiHEZf4Snyt+XzuTnChSP/N8OLFk+TCKLfNPf2r9km2OzXD3GB0BEx+X+Cj2fec2yKyM/ri04FeHp/PEnKOlNSgkxHb28eOWr+boC9f+A8cvq2SNBTYJuQ0nQL/5/Kyjo5OWEVrVovGnP9WaNBb96C9zb9heO4Dis7kZJGSZjMHzsft2CuVbQvk2eHx7HJEbUmJUO74R68bGro5z/W28HaI/veiwXXl2GWL6z8oM7SCuKP8XFA8emLFmJLG/A56WfonWnPWVv5g7pJemgAK5TTwTPdQjgP+NKgjjMCEbLAEYLCM2uOrvkTme4fm6qcP2SAZz37VjfRvC5k8PfLxjJgEENAB4NkEgK/uh/jCO7YkzPvdCvTYC3AtNz9ts6AlOP4jX/WSEnu3tornhOBKoF+rBcxwaMgEEwDI8tNRR6ZYMJ5oSBHJ9wOfTooEwXOMBoG4DSnLnaFAWG+EOxCSOhs9qY4JjFz75qd/IYCSEeJ+4GwJE9ky8cnJYcuzCJz9lg5Nj65SczIsBQR2gQCjo+TF8/lOPwUpNyaHV6cRz+LSpiTqGE4qfWNupFvnZSRs2MCgaddPoOQXEPITmDInWgR1vPf84fSoFUEOPjmGV301XlvLWTie7nONf8ZNpzSQWzSC71PvC41+zZ5JsIwxRH/s0TtmPb9km7BwtIxJLH5s0z5iOt+jd8eHdtAaaDFgfa7XPcY+3+XtpVpscYK/61z5HPd6iD47xB8fFBxNXy6kg0ueXDZ81L/yMW+8ZiQqveNTWO47hSBeY0U/o7Rz/OgWWfBKup3/rrhFUUf0tk/ftu2M4Uf/pX/7t9uv67utav7i8/3ftX/7t7v72P5aLNdpa+fc5Tjym4NVQ25FJua4Ii72yo7gQfegd4egq8ZIIWMeBgYpbraR1imibenUm7sjEzvRkJ6YdLNjDrns/iv9nGbafoaBZ5qmL8Ny2APz1zVlqLiuep4firE1iOxZevZ7vvGReau9QVFDSniWBxNfpR3Nk8Dn2eUZ31P1Tmb4zPfVir5bvt9mdwMcO8Hbx/idyd1F0VqM5XJ/MLn//v9ktN7vT/VOc1dneDpl7mXu7H1TnD5H9tPvh9L17enrq7uLNwAlWQ+fbu7VN4B96EMKB0lbHy089bfqrMzs+3pkNw1W25LAYonnocfj0DOXsXHR6gm/vNJG1xPcN2WCKqWdA3+bNhGNtHWMXSSgbvDN3WDPbw27Z17nl/lnsVmtBULAUd8NlyPYM/yjEHT/Z8f64Hu9IkbrRV5xph2biGKEFAuBZwDNfhu1hqcPIg62iVZsVsu9AjamBHGgcanOPrPlRyzpp/Nd3P/7l2XXQpyBEsazgx6fz9CgAQNdW2N4OPvq6/nz84dvRX1IBeSdfuDAl5tz1rQTWKHz9xXyBD6DdpZ/dQRt/wsCLMFlz7OoF00NJAQjjl5UJ/4WCiuFD2fQBFICZr2IQ/BnCr/w9ESULbI3EiVcgjvHmZQ8umjhUY0wsEFZiZsCGZjl5iXK2dERriqux4+ZmaOrZESwzTDWisgIzragG8FERjIvebJUvna2WraPZ0ery+u7qcnG5/k1frb+ikxd397d3y/v15XJ19PHo79+OSuHgPn6DD77Bka7xCGB59c2HX4zQRocKI/T4I/qBPkD/wRYgsOFX1sOVb6aL7dmLj/kvO2A++Ohwrf52/nb+Jn88y39BB/pug3q62kA7e/6P9AcUcHSRFnDukCPbDRzbtOMXjPvs5Ozt/B0sYbyg/wNmSYoCObREMAf+85AFwIKSUAbPioKGzy8ikmkpQQEFkIOqXpzbQ8bwQ3tne4aTfewljgOfZlUEPjid4fQxHInAv47PTs/O3r398Obdm3/MeinHLqVZ0zIGwYd3J2fvv4cQWPXna7H366W+KM5pD2MPyZ+9fXN69v5tX+3Y9plyHZYfw/GH5sAPb89Ovv/ww+kACOARqd8bnpXtEvRWf/rh3embsw+np+/7qq+1VwPMD9X+ALmf9FZOWYgfYPmTsx/OTt6/eXfyj/86+sf/BzXyP+4==END_SIMPLICITY_STUDIO_METADATA
